### HTML ENDPOINT
### Designed for the web browser. Provide the GUI to the user
### Retrieve a document

### HTML API DOCUMENTATION
GET http://127.0.0.1:3000/api/posts
###

GET http://127.0.0.1:3000/api/posts/featured

###

GET http://127.0.0.1:3000/api/users

###

GET http://127.0.0.1:3000/api/posts/id/6811109e65fd9a8ee7bb1b8c

###

### API ENDPOINTS
### Designed to provide data functionality to all apps (phone, web, thrid party websites)


###         TAGS API ENDPOINT

POST http://127.0.0.1:3000/api/tags
Content-Type: application/json

{
    "content" : "I am wanting to sell my boat for 200 pounds. But you need to come and get it."
}

###

GET http://127.0.0.1:3000/api/tags
Content-Type: application/json

###

POST http://127.0.0.1:3000/api/users/signup
Content-Type: application/json

{
    "content" : {
        "email" : "bobjones1@gmail.com",
        "password" : "!1234abcd!"
    }
}

##