### HTML ENDPOINT
### Designed for the web browser. Provide the GUI to the user
### Retrieve a document

### HTML API DOCUMENTATION
GET http://127.0.0.1:3000/api/posts
###

GET http://127.0.0.1:3000/api/posts/featured

###

GET http://127.0.0.1:3000/api/users/user/6814f96c6d6b4ef6e3209b1b

###

GET http://127.0.0.1:3000/api/posts/id/6811109e65fd9a8ee7bb1b8c

###

### API ENDPOINTS
### Designed to provide data functionality to all apps (phone, web, thrid party websites)


###         TAGS API ENDPOINT

POST http://127.0.0.1:3000/api/tags
Content-Type: application/json

{
    "content" : "I am wanting to sell my boat for 200 pounds. But you need to come and get it."
}

###

GET http://127.0.0.1:3000/api/tags
Content-Type: application/json

###

POST http://127.0.0.1:3000/api/users/signup
Content-Type: application/json

{
    "content" : {
        "username": "TestUser",
        "password": "!123ABC!",
        "email":"test@user.com",
        "number":"111-111-1111",
        "birthday":"01-01-2001"
    }
}

###

POST http://127.0.0.1:3000/api/users/signin
Content-Type: application/json

{
    "content" : {
        "email" : "test@user.com",
        "password": "!123ABC!"
    }
}

###

POST http://127.0.0.1:3000/api/users/auth
Content-Type: application/json

{
    "content": {
        "token" : "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbiI6IiIsInVzZXIiOnsiZW1haWwiOiJ0ZXN0QHVzZXIuY29tIiwiaWQiOiI2ODE1NTQ4M2VjODkwMGNjZjRlNTIzYWYifSwiaWF0IjoxNzQ2MzEyNDI1LCJleHAiOjE3NDYzMTYwMjV9.Gv5J3Iv6U7vkKDaBlVg_fZMPKYheRuifQVN9PumQ0Bo"
    }
}

###

POST http://127.0.0.1:3000/api/posts/post
Content-Type: application/json

{
    "content": {
        "_id": "new ObjectId('6811109e65fd9a8ee7bb1b8c')",
        "created_by": "Joe Schmoe",
        "date_created": "",
        "time_created": "new Timestamp({ t: 1745949536, i: 8 })",
        "post_title": "Yeet",
        "type": "Post",
        "city": "Babylon",
        "state": "Sumeria",
        "price": "N/A",
        "post_views": "1000",
        "is_job": "false",
        "img": "./assets/images/avatar1.jpg",
        "post_content": "",
        "is_featured": "true"
    }
}

###