### HTML ENDPOINT
### Designed for the web browser. Provide the GUI to the user
### Retrieve a document

### HTML API DOCUMENTATION
GET http://127.0.0.1:3000/api/posts
###

GET http://127.0.0.1:3000/api/posts/featured

###

GET http://127.0.0.1:3000/api/users/user/6814f96c6d6b4ef6e3209b1b

###

GET http://127.0.0.1:3000/api/posts/id/6811109e65fd9a8ee7bb1b8c

###

GET http://127.0.0.1:3000/api/chats/chat/681b9801de5e1fff96a3805b

###

GET http://127.0.0.1:3000/api/chats/681d68636d37e1a049f52271

###

GET http://127.0.0.1:3000/api/posts/user_posts/681ad0d684940469a86b4dad

###

POST http://127.0.0.1:3000/api/posts/user_posts/681ad0d684940469a86b4dad
Authorization: 

###

### API ENDPOINTS
### Designed to provide data functionality to all apps (phone, web, thrid party websites)


###         TAGS API ENDPOINT

POST http://127.0.0.1:3000/api/tags
Content-Type: application/json

{
    "content" : "I am wanting to sell my boat for 200 pounds. But you need to come and get it."
}

###

GET http://127.0.0.1:3000/api/tags
Content-Type: application/json

###

POST http://127.0.0.1:3000/api/users/signup
Content-Type: application/json

{
    "content" : {
        "username": "TestUser",
        "password": "!123aBC!",
        "email":"TEST1@user.com",
        "number":"111-111-1111",
        "birthday":"01-01-2001"
    }
}

###

POST http://127.0.0.1:3000/api/users/signin
Content-Type: application/json

{
    "content" : {
        "email" : "test@user.com",
        "password": "!123ABC!"
    }
}

###

POST http://127.0.0.1:3000/api/users/auth
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7ImVtYWlsIjoidGVzdEB1c2VyLmNvbSIsInVzZXJuYW1lIjoiVGVzdFVzZXIiLCJpZCI6IjY4MTU1NDgzZWM4OTAwY2NmNGU1MjNhZiJ9LCJpYXQiOjE3NDY1NTY3MzcsImV4cCI6MTc0NjU2MDMzN30.r7tizKkGaK44BYX_-HOffaivgFCPlSGvtz1RJ-d7e8Q
Content-Type: application/json

{
    "content": "test"
}

###

POST http://127.0.0.1:3000/api/users/reauth
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7ImVtYWlsIjoidGVzdEB1c2VyLmNvbSIsInVzZXJuYW1lIjoiVGVzdFVzZXIiLCJpZCI6IjY4MTU1NDgzZWM4OTAwY2NmNGU1MjNhZiJ9LCJpYXQiOjE3NDY1NTY3MzcsImV4cCI6MTc0NjU2MDMzN30.r7tizKkGaK44BYX_-HOffaivgFCPlSGvtz1RJ-d7e8Q
Content-Type: application/json
### 

POST http://127.0.0.1:3000/api/posts/post
Content-Type: application/json

{
    "content": {
        "user_id" : "681a3252697ff9b8110229b6",
        "created_by": "Joe Schmoe",
        "post_title": "TEST",
        "type": "Post",
        "city": "Babylon",
        "state": "Sumeria",
        "price": "$1",
        "is_job": "false",
        "img": "./assets/images/avatar1.jpg",
        "post_content": "Lorem Ipsum",
        "is_featured": "false"
    }
}

###

POST http://localhost:3000/api/users/reauth
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7ImVtYWlsIjoidGVzdEB1c2VyLmNvbSIsInVzZXJuYW1lIjoiVGVzdFVzZXIiLCJpZCI6IjY4MTU1NDgzZWM4OTAwY2NmNGU1MjNhZiJ9LCJpYXQiOjE3NDY3MTg4ODUsImV4cCI6MTc0NjcxOTE4NX0.O9jteydIWMlRhBWwKN-JFL246K-R9UbjtZWtUpHi6LE

###

POST http://localhost:3000/api/chats/newChat
Content-Type: application/json

{
    "content" : {
        "userA_id" : "TEST4",
        "userB_id" : "TEST4",
        "userA_name" : "TEST4",
        "userB_name" : "TEST4",
        "messages" : [{
            "content" : "TEST4",
            "sender_name" : "TEST4",
            "sender_id" : "TEST4"
        }]
    }
}

###

PUT http://localhost:3000/api/chats/681d68636d37e1a049f52271
Content-Type: application/json

{
    "content" : {
        "chat_id" : "681d68636d37e1a049f52271",
        "messages" : [{
            "content" : "TEST5",
            "sender_name" : "TEST5",
            "sender_id" : "TEST5"
        }]
    }
}

###

DELETE http://localhost:3000/api/posts/user/68155483ec8900ccf4e523af/delete/681cd50459d9f28971d355dd
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7ImVtYWlsIjoidGVzdEB1c2VyLmNvbSIsInVzZXJuYW1lIjoiVGVzdFVzZXIiLCJpZCI6IjY4MTU1NDgzZWM4OTAwY2NmNGU1MjNhZiJ9LCJpYXQiOjE3NDY3NDc1NzksImV4cCI6MTc0Njc0Nzg3OX0.LGjkCTiEtTNGKtbMLQwvwhR5f6A5OUs_FC5Edd7q5hI

###

DELETE http://localhost:3000/api


###